version: '3.8'

services:
  database:
    image: mysql:latest
    container_name: gestion_recettes
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
    volumes:
      - db:/var/lib/mysql
    ports:
      - '3307:3306'

  api:
    image: recette-api
    container_name: recette-api
    build: .
    volumes:
      - .:/src/app
    environment:
      DB_HOST: ${DB_HOST}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      DB_PORT: ${DB_PORT}
    ports:
      - '3020:3020'
    depends_on:
      - database

volumes:
  db:
